FROM node:16-alpine
WORKDIR /usr/src/app
COPY package.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
RUN npm install
ENV PATH=/usr/src/app/node_modules/.bin:$PATH
WORKDIR /usr/src/app/dev
COPY src ./src
COPY prisma ./prisma
COPY .env.example ./.env
RUN prisma migrate deploy
EXPOSE ${PORT}
CMD ["npm", "run", "start:dev"]