version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:8080/
  music_app:
      image: music_app
      container_name: music_app
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        PORT: "${PORT}"
        POSTGRES_USER: "${POSTGRES_USER}"
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_HOST: db
        POSTGRES_PORT: "${POSTGRES_PORT}"
        POSTGRES_DB: "${POSTGRES_DB}"
      depends_on:
        - music_db
      volumes:
        - music_app:/var/lib/music_app/data
      networks:
        - music_network
      restart: always
      ports:
        - "${PORT}:${PORT}"

  music_db:
    image: music_db
    container_name: music_db
    build:
      context: .
      dockerfile: ./music_db/Dockerfile
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
    volumes:
      - music_db:/var/lib/music_db/data
    networks:
      - music_network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  music_db:
    driver: local
    name: 'music_db_volume'
  music_app:
    driver: local
    name: 'music_app_volume'
    
networks:
  music_network:
    name: 'music_network'
    driver: bridge