version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:8080/

  postgres:
    image: music_postgres
    container_name: music_postgres_container
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    volumes:
      - postgres:/var/lib/music_postgres_container/data
    networks:
      - postgres
    env_file:
      - docker.env
    ports:
      - '8080:8080'
  app:
    image: music_app
    container_name: music_app_container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    volumes:
      - app:/var/lib/app/data
    networks:
      - postgres
    restart: always

volumes:
  postgres:
    name: 'music_postgres_volume'
  app:
    name: 'music_app_volume'
networks:
  postgres:
    name: 'musiclibrary_network'
    driver: bridge